# CMake generated Testfile for 
# Source directory: /home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests
# Build directory: /home/dev/graphdb/FilterVectorCode_refactor/UNG/build-final/croaring_build/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(cpp_unit "cpp_unit")
set_tests_properties(cpp_unit PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;49;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;7;add_cpp_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(cpp_random_unit "cpp_random_unit")
set_tests_properties(cpp_random_unit PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;49;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;8;add_cpp_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(cpp_example1 "cpp_example1")
set_tests_properties(cpp_example1 PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;49;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;9;add_cpp_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(cpp_example2 "cpp_example2")
set_tests_properties(cpp_example2 PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;49;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;10;add_cpp_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(c_example1 "c_example1")
set_tests_properties(c_example1 PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;28;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;11;add_c_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(cbitset_unit "cbitset_unit")
set_tests_properties(cbitset_unit PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;28;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;12;add_c_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(array_container_unit "array_container_unit")
set_tests_properties(array_container_unit PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;28;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;13;add_c_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(bitset_container_unit "bitset_container_unit")
set_tests_properties(bitset_container_unit PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;28;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;14;add_c_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(mixed_container_unit "mixed_container_unit")
set_tests_properties(mixed_container_unit PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;28;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;15;add_c_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(run_container_unit "run_container_unit")
set_tests_properties(run_container_unit PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;28;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;16;add_c_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(toplevel_unit "toplevel_unit")
set_tests_properties(toplevel_unit PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;28;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;17;add_c_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(util_unit "util_unit")
set_tests_properties(util_unit PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;28;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;18;add_c_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(format_portability_unit "format_portability_unit")
set_tests_properties(format_portability_unit PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;28;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;19;add_c_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(robust_deserialization_unit "robust_deserialization_unit")
set_tests_properties(robust_deserialization_unit PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;28;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;20;add_c_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(container_comparison_unit "container_comparison_unit")
set_tests_properties(container_comparison_unit PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;28;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;21;add_c_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(add_offset "add_offset")
set_tests_properties(add_offset PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;28;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;22;add_c_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(art_unit "art_unit")
set_tests_properties(art_unit PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;49;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;23;add_cpp_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(roaring64_unit "roaring64_unit")
set_tests_properties(roaring64_unit PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;49;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;24;add_cpp_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(roaring64_serialization "roaring64_serialization")
set_tests_properties(roaring64_serialization PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;49;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;25;add_cpp_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(threads_unit "threads_unit")
set_tests_properties(threads_unit PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;40;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
add_test(realdata_unit "realdata_unit")
set_tests_properties(realdata_unit PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tools/cmake/FindCTargets.cmake;28;add_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;47;add_c_test;/home/dev/graphdb/FilterVectorCode_refactor/UNG/codes/third_party/CRoaring/tests/CMakeLists.txt;0;")
